### PR TITLE
[WIP] Add Translations Portugues-BR

### PR DESCRIPTION
**Pull request by crashzk**

### CODE REVIEW

**Comment by asheroto** [comment]
Hey there, thanks for working on this!  I updated the README file which should help explain things better.  Usually pull requests are made when you want to merge the file into the main repo.  Or in this case of seDirector Translations, whenever a good handful of translations have been made.

Going to close this pull request since there's only a few translations in this file, but you're doing on the right path! 😊

**Comment by crashzk** [comment]
Yes, I understand, it was still an ongoing process, I'm still translating this case.

In any case translating most I send a new PR to the project, thank you.

**Comment by asheroto** [comment]
Cool. As long as you get the major strings translated, we'll merge them. In the JSON file there is a UI object. Those are the  main ones we would like translated. And if there are any strings that would be difficult to understand.

**Comment by asheroto** [comment]
Hey @crashzk, switched the system to use POEditor, it's a lot easier to translate now!  See the README.  Thank you!

**Pull request closed without merging**
